export const DEFAULT_ALLOWLIST = Object.freeze({
  search: Object.freeze([
    "google.com",
    "bing.com",
    "duckduckgo.com",
  ]),
  llm: Object.freeze([
    "chatgpt.com",
    "claude.ai",
    "gemini.google.com",
    "perplexity.ai",
    "copilot.microsoft.com",
  ]),
  qa: Object.freeze([
    "stackoverflow.com",
    "stackexchange.com",
    "serverfault.com",
    "stackapps.com",
    "superuser.com",
    "askubuntu.com",
    "mathoverflow.net",
  ]),
  code_and_packages: Object.freeze([
    "github.com",
    "gitlab.com",
    "npmjs.com",
    "pypi.org",
  ]),
  documentation: Object.freeze([
    "developer.mozilla.org",
    "docs.github.com",
    "docs.gitlab.com",
    "docs.python.org",
    "learn.microsoft.com",
    "developers.google.com",
  ]),
  reference: Object.freeze(["wikipedia.org"]),
});

export const DEFAULT_DENYLIST = Object.freeze({
  finance_accounts: Object.freeze([
    "bankofamerica.com",
    "chase.com",
    "wellsfargo.com",
    "capitalone.com",
    "citibank.com",
    "discover.com",
    "ally.com",
    "americanexpress.com",
    "paypal.com",
    "venmo.com",
    "fidelity.com",
    "schwab.com",
    "vanguard.com",
    "robinhood.com",
    "coinbase.com",
    "wise.com",
  ]),
  health_and_medical: Object.freeze([
    "mychart.com",
    "mychart.org",
    "patientportal.net",
    "healthvault.com",
    "zocdoc.com",
    "webmd.com",
    "mayoclinic.org",
    "kaiserpermanente.org",
  ]),
  adult: Object.freeze([
    "pornhub.com",
    "xvideos.com",
    "xnxx.com",
    "redtube.com",
    "onlyfans.com",
  ]),
  webmail: Object.freeze([
    "mail.google.com",
    "outlook.live.com",
    "outlook.office.com",
    "mail.yahoo.com",
    "mail.proton.me",
    "protonmail.com",
    "fastmail.com",
    "mail.zoho.com",
  ]),
  private_docs_and_storage: Object.freeze([
    "drive.google.com",
    "docs.google.com",
    "dropbox.com",
    "onedrive.live.com",
    "icloud.com",
    "box.com",
    "office.com",
    "sharepoint.com",
  ]),
});

export const SENSITIVE_HOST_LABELS = Object.freeze([
  "account",
  "accounts",
  "auth",
  "login",
  "mail",
  "myaccount",
  "patient",
  "portal",
  "signin",
  "sso",
]);

export const SENSITIVE_PATH_SEGMENTS = Object.freeze([
  "account",
  "accounts",
  "auth",
  "login",
  "logout",
  "password",
  "reset-password",
  "signin",
  "sign-in",
  "signup",
  "sign-up",
  "sso",
]);
